services:
  # The Python/Flask/Gunicorn Application Service
  app:
    build: . # Build the image from the Dockerfile in the current directory
    restart: unless-stopped
    volumes:
      # Named volume for all static content. App service can write to it.
      - static_volume:/app/static
      # Named volume for the configuration file.
      - config_volume:/app/config
    env_file:
      - ./.env # Load environment variables from the .env file
    # Expose port 8000 only to the internal Docker network
    expose:
      - "8000"

  # The Nginx Reverse Proxy Service
  nginx:
    image: nginx:stable-alpine # Use the official lightweight Nginx image
    restart: unless-stopped
    ports:
      # Map port 8080 on the host machine to port 80 in the Nginx container
      - "8080:80"
    volumes:
      # Mount the custom Nginx config from the host into the container (read-only)
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount the shared static files volume so Nginx can serve them directly (read-only)
      - static_volume:/app/static:ro
    depends_on:
      - app # Wait for the 'app' service to start before starting nginx

# Define the named volumes
volumes:
  static_volume:
  config_volume:
