version: '3.8'

services:
  # The Python/Flask/Gunicorn Application Service
  app:
    build: . # Build the image from the Dockerfile in the current directory
    restart: unless-stopped
    expose:
      - "8000" # Expose port 8000 to the internal Docker network
    volumes:
      # Named volumes for persistent data
      - logos_volume:/app/static/uploads # Persist uploaded logos
      - config_volume:/app/config    # Persist the logo configuration
    env_file:
      - ./.env # Load environment variables from the .env file

  # The Nginx Reverse Proxy Service
  nginx:
    image: nginx:stable-alpine # Use the official lightweight Nginx image
    restart: unless-stopped
    ports:
      # Map port 8080 on the host machine to port 80 in the Nginx container
      # You can change 8080 to any other unused port on your host (e.g., 80)
      - "8080:80"
    volumes:
      # Mount the custom Nginx config from the host into the container (read-only)
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount the static files volume so Nginx can serve them directly (read-only)
      # This volume is shared with the 'app' service
      - logos_volume:/app/static/uploads:ro
    depends_on:
      - app # Wait for the 'app' service to start before starting nginx

# Define the named volumes
volumes:
  logos_volume:
  config_volume:
